// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
)

type Pattern struct {
	UserID       uuid.UUID
	ID           uuid.UUID
	Instructions *string
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	HashedPassword string
	Salt           *string
}
