// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Pattern struct {
	UserID       pgtype.UUID
	ID           pgtype.UUID
	Instructions pgtype.Text
}

type User struct {
	ID             pgtype.UUID
	Username       pgtype.Text
	Email          pgtype.Text
	HashedPassword pgtype.Text
	Salt           pgtype.Text
}
